### ISSUE TITLE
Ruby 2.6 

### ISSUE THREAD

**Issue by mattheworiordan** [brightbox/deb-ruby2.5#1]
Hey @johnl.  I've been a long time user of your Ubuntu Brightbox packages.  Any idea when / if you guys will be publishing an Ruby 2.6 package for Ubuntu v*?

**Comment by johnl** [comment]
Hi Matthew,

Work on 2.6 is already underway. There are packages for xenial and bionic
in the experimental PPA right now, though I literally got them to build and
haven't even tested them yet! Feel free to try them and feed back :)

Otherwise, I'd expect to have them properly tested  and finished by the end
of this week or the next.

**Comment by mattheworiordan** [comment]
@johnl fortunately the area we needed the 2.6 update is for internal use and not production facing, so using the experimental branch worked perfectly.  Thanks @johnl, I'll keep an eye out for the mainline release.

Have a good new year!
